{{- if .Values.redis.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ tpl (.Values.redis.secret.name) . }}"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cvat.labels" . | nindent 4 }}
type: generic
stringData:
  password: {{ .Values.redis.secret.password | toString | toYaml }}
{{- end }}
